name: gha-gitops-manifest-update
description: Iterates over YAML manifests (Kubernetes Deployment, ArgoCD Application, or ArgoCD ApplicationSet) and updates their image/tag - also renders manifests.

inputs:
  #image
  tag:
    type: string
    description: e.g. 1.2.3, 1.2.3-branch-name.12
    required: true
  tag-override:
    type: string
    description: e.g. latest, latest-dev
  image-registry:
    type: string
    description: e.g. ghcr.io/gh-user, xyz.azurecr.io or docker.io
    required: true
  image-repository:
    type: string
    description: e.g. [optional-prefix/]myimage
    required: true
  #chart
  chart-registry:
    type: string
    description: e.g. ghcr.io/gh-user, xyz.azurecr.io or docker.io
  chart-registry-username:
    type: string
  chart-registry-password:
    type: string
  chart-repository:
    type: string
    description: e.g. [optional-prefix/]charts/myname
  #manifest
  manifest-paths:
    type: string
    description: Space-separated YAML manifests which need to be updated e.g. src/workloads/manifest1.yaml src/workloads/manifest2.yaml
    required: true
  namespace:
    type: string
    description: Destination Kubernetes namespace for the application.
    required: true
  #tooling
  devcontainer-path:
    type: string
    description: e.g. .devcontainer/devcontainer.json
    default: .devcontainer/devcontainer.json
  #git
  git-repo-update:
    type: boolean
    description: If 'false' then skips the git operations entirely, e.g. action runs in demo mode
    default: true
  git-user-name:
    type: string
    description: e.g. GitHub Actions Bot
    default: GitHub Actions Bot
  git-user-email:
    type: string
    description: e.g. github-actions[bot]@users.noreply.github.com
    default: github-actions[bot]@users.noreply.github.com
  git-branch-name:
    type: string
    description: e.g. main
    default: main
  git-working-directory:
    type: string
    description: Working directory for git operations e.g. gitops/
    default: .

runs:
  using: composite
  steps:

    - name: setup yq (1 of 3)
      shell: bash
      run: |
        GIT_DIR="${{ inputs.git-working-directory }}"
        GIT_DIR="${GIT_DIR%/}"
        if [[ "$GIT_DIR" != "." ]]; then
          FILE="$GIT_DIR/${{ inputs.devcontainer-path }}"
        else
          FILE="${{ inputs.devcontainer-path }}"
        fi
        if [[ -f "$FILE" ]]; then
          echo "$FILE exists"
        else
          echo "::error file=$FILE::yq version is managed by the devcontainer.json, '$FILE' is therefore required!"
          exit 1
        fi
        echo "DEVCONTAINER_PATH=$FILE" >> $GITHUB_ENV

    - name: setup yq (2 of 3) #pull version from devcontainer.json
      shell: bash
      run: |
        npm install --global json5
        json5 -c ${{ env.DEVCONTAINER_PATH }}
        VERSION_TO_INSTALL=$(cat ${{ env.DEVCONTAINER_PATH }} | jq -r '.features[] | select(.yqVersion | . != null).yqVersion')
        echo "VERSION_TO_INSTALL=$VERSION_TO_INSTALL" >> $GITHUB_ENV
        echo "VERSION_TO_INSTALL=$VERSION_TO_INSTALL"

    - name: setup yq (3 of 3)
      shell: bash
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/${{ env.VERSION_TO_INSTALL }}/download/yq_linux_amd64 -O /usr/bin/yq \
          && sudo chmod +x /usr/bin/yq

    - name: setup helm (1 of 2) #pull version from devcontainer.json
      shell: bash
      run: |
        HELM_VERSION=$(cat ${{ env.DEVCONTAINER_PATH }} | jq -r '.features[] | select(.helm | . != null).helm')
        echo "HELM_VERSION=$HELM_VERSION" >> $GITHUB_ENV
        echo "HELM_VERSION=$HELM_VERSION"

    - name: setup helm (2 of 2)
      uses: azure/setup-helm@v5
      with:
        version: ${{ env.HELM_VERSION }}

    #1. update the argocd application targetRevision to reflect the new helm chart version
    #2. expand out the helm chart with new helm chart version (optional)
    - name: update manifest(s)
      shell: bash
      env:
        GIT_WORKING_DIRECTORY: ${{ inputs.git-working-directory }}
        MANIFEST_PATHS: ${{ inputs.manifest-paths }}
        TAG: ${{ inputs.tag }}
        TAG_OVERRIDE: ${{ inputs.tag-override }}
        IMAGE_REGISTRY: ${{ inputs.image-registry }}
        IMAGE_REPOSITORY: ${{ inputs.image-repository }}
        CHART_REGISTRY: ${{ inputs.chart-registry }}
        CHART_REGISTRY_USERNAME: ${{ inputs.chart-registry-username }}
        CHART_REGISTRY_PASSWORD: ${{ inputs.chart-registry-password }}
        CHART_REPOSITORY: ${{ inputs.chart-repository }}
        NAMESPACE: ${{ inputs.namespace }}
      run: "${{ github.action_path }}/.scripts/update-manifests.sh"

    - name: repo update
      if: inputs.git-repo-update == 'true'
      shell: bash
      env:
        GIT_WORKING_DIRECTORY: ${{ inputs.git-working-directory }}
        GIT_USER_NAME: ${{ inputs.git-user-name }}
        GIT_USER_EMAIL: ${{ inputs.git-user-email }}
        GIT_BRANCH_NAME: ${{ inputs.git-branch-name }}
        NAMESPACE: ${{ inputs.namespace }}
        IMAGE_REPOSITORY: ${{ inputs.image-repository }}
        TAG: ${{ inputs.tag }}
      run: "${{ github.action_path }}/.scripts/repo-update.sh"
