name: gha-gitops-manifest-update
description: Updates image tags in gitops manifests and optionally pushes changes to the git repository.

inputs:
  image-registry:
    type: string
    description: e.g. ghcr.io/gh-user, xyz.azurecr.io or docker.io
    required: true
  image-repository:
    type: string
    description: e.g. [optional-prefix/]myimage
    required: true
  tag-override:
    type: string
    description: e.g. latest, latest-dev, 1.2.3
    required: true
  devcontainer-path:
    type: string
    description: e.g. .devcontainer/devcontainer.json
    default: .devcontainer/devcontainer.json
  manifest-paths:
    type: string
    description: Space-separated YAML manifests which need to be updated e.g. src/workloads/manifest1.yaml src/workloads/manifest2.yaml
    required: true
  tag:
    type: string
    description: e.g. 1.2.301-feature-my-feature.12
    required: true
  git-repo-update:
    type: boolean
    description: If 'false' then skips the git operations entirely, e.g. action runs in demo mode
    default: true
  git-user-name:
    type: string
    description: e.g. GitHub Actions Bot
    default: GitHub Actions Bot
  git-user-email:
    type: string
    description: e.g. github-actions[bot]@users.noreply.github.com
    default: github-actions[bot]@users.noreply.github.com
  git-branch-name:
    type: string
    description: e.g. main
    default: main

runs:
  using: composite
  steps:

    - name: setup yq (1 of 3)
      shell: bash
      run: |
        FILE=${{ inputs.devcontainer-path }}
        if [[ -f "$FILE" ]]; then
          echo "$FILE exists"
        else
          echo "::error file=${{ inputs.devcontainer-path }}::yq version is managed by the devcontainer.json, '$FILE' is therefore required!"
          exit 1
        fi

    - name: setup yq (2 of 3) #pull version from devcontainer.json
      shell: bash
      run: |
        npm install --global json5
        json5 -c ${{ inputs.devcontainer-path }}
        VERSION_TO_INSTALL=$(cat ${{ inputs.devcontainer-path }} | jq -r '.features[] | select(.yqVersion | . != null).yqVersion')
        echo "VERSION_TO_INSTALL=$VERSION_TO_INSTALL" >> $GITHUB_ENV
        echo "VERSION_TO_INSTALL=$VERSION_TO_INSTALL"

    - name: setup yq (3 of 3)
      shell: bash
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/${{ env.VERSION_TO_INSTALL }}/download/yq_linux_amd64 -O /usr/bin/yq \
          && sudo chmod +x /usr/bin/yq

    - name: manipulate deployment
      shell: bash
      run: |
        MANIFEST_PATHS=(${{ inputs.manifest-paths }})
        for MANIFEST_PATH in "${MANIFEST_PATHS[@]}"
        do

          echo "now processing manifest..."
          export MANIFEST_PATH=$MANIFEST_PATH                                        # e.g. src/workloads/authenticator.yaml
          export REGISTRY=${{ inputs.image-registry }}                               # e.g. ghcr.io/f2calv
          export REPOSITORY=$REGISTRY/${{ inputs.image-repository }}                 # e.g. ghcr.io/f2calv/authenticator
          export TAG=${{ inputs.tag }}                                               # e.g. 1.2.301-feature-my-feature.12
          export TAG_OVERRIDE=${{ inputs.tag-override }}                             # e.g. latest, latest-dev, 1.2.3
          export IMAGE=$REPOSITORY:$TAG_OVERRIDE                                     # e.g. ghcr.io/f2calv/authenticator:1.2.3

          echo "MANIFEST_PATH=$MANIFEST_PATH"
          echo "REGISTRY=$REGISTRY"
          echo "REPOSITORY=$REPOSITORY"
          echo "TAG=$TAG"
          echo "TAG_OVERRIDE=$TAG_OVERRIDE"
          echo "IMAGE=$IMAGE"

          if [[ ! -f $MANIFEST_PATH ]]; then
             echo "::warning title=file $MANIFEST_PATH::File $MANIFEST_PATH does not exist!"
             continue
          fi

          #update the image tag
          yq -i '. | select(.kind == "Deployment") as $deployment | select(.kind != "Deployment") as $other | $deployment.spec.template.spec.containers[] |= select(.name == "primary").image=env(IMAGE) | ($deployment, $other)' $MANIFEST_PATH

          #update the TAG env variable so we can track a deployment of a new image that has it's full sem ver tag overriden by tagged tag-override, e.g. latest-dev
          yq -i '. | select(.kind == "Deployment") as $deployment | select(.kind != "Deployment") as $other | $deployment.spec.template.spec.containers[] |= select(.name == "primary").env[] |= select(.name == "TAG").value=env(TAG) | ($deployment, $other)' $MANIFEST_PATH

          cat $MANIFEST_PATH

        done

    - name: repo update
      if: inputs.git-repo-update == 'true'
      shell: bash
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          git config --global user.name "${{ inputs.git-user-name }}"
          git config --global user.email "${{ inputs.git-user-email }}"
          git checkout ${{ inputs.git-branch-name }}
          git add --all
          git commit -m "bump '${{ inputs.image-repository }}' to '${{ inputs.tag }}'"
          git push -v --progress
        else
          echo "::warning title=git push::No changes to push."
        fi
